--Hospital management wants to know:

--Which doctor sees the most patients?

--What illness is most common?

--Average hospital stay duration?


select * from hospital_patient_management

COPY hospital_patient_management
FROM 'C:\Program Files\PostgreSQL\18\hospital_patient_management_dataset.csv'
DELIMITER ',' CSV HEADER;

--count the total number of patient in the hospital
select count(*) as total_Patients
from hospital_patient_management;


--count how many patient are in each department
select department, count(*) as total_patient_per_dept
from hospital_patient_management
group by department
order by total_patient_per_dept desc;

--count the number of patient that is diagnosed in a department 
select department, diagnosis, count(*) as diagnosis_per_dept
from hospital_patient_management
group by department, diagnosis
order by diagnosis_per_dept desc;

--count the number of diagnosis for each department
select department, 
string_agg(distinct diagnosis, ', '), count(*) as diagnosis
from hospital_patient_management
group by department
order by diagnosis desc;

--count the number of patient that each doctor handled
select doctor, string_agg(distinct patient_name, ', '), count(*) as patient_handled
from hospital_patient_management
group by doctor
order by patient_handled desc;

--count the number of patient for each admission_type
select admission_type, count(*) as total_cases_per_AT
from hospital_patient_management
group by admission_type
order by total_cases_per_AT desc;

--count the total number of patient admitted in a month
select date_trunc('month', admission_date) as month_admitted,
count(*) as total_admission_per_month
from hospital_patient_management
group by month_admitted
order by total_admission_per_month desc;


--check the total number of patient that is admitted in a day
select to_char(admission_date, 'day') as day_admitted,
count(*) as total_admission_per_day
from hospital_patient_management
group by day_admitted
order by total_admission_per_day desc;


--count the total number of patient that is discharged in a month
select date_trunc ('month', discharge_date) as month_discharged,
count(*) as total_discharged_per_day
from hospital_patient_management
group by month_discharged
order by total_discharged_per_day desc;


--count the total number of patient discharged in a month
select to_char(discharge_date, 'day')as day_discharged,
count(*) as total_discharge_per_day
from hospital_patient_management
group by day_discharged
order by total_discharge_per_day desc;


--the total number of days that each patient stayed in the hospital
select patient_name, sum(discharge_date - admission_date) as total_stay_day
from hospital_patient_management
group by patient_name
order by max(discharge_date - admission_date) desc;

--the total number of days that all the patient stayed in the hospital
select sum(discharge_date - admission_date) as total_stay_day
from hospital_patient_management

--the total revenue or money generated by each disgnosis in a department for treatment
select department, diagnosis, sum(treatment_cost) as total_revenue_per_diagnosis
from hospital_patient_management
group by department, diagnosis
order by total_treat_revenue desc;

--the total revenue in a department for treatment
select department, 
string_agg(distinct diagnosis, ', '),
sum(treatment_cost) as total_revenue_per_department
from hospital_patient_management
group by department
order by total_revenue_per_department desc;

--check the patient with the highest treatment cost
select patient_name, treatment_cost, diagnosis, department,
rank() over(order by treatment_cost desc) as cost_rank
from hospital_patient_management;


